env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
    - go mod tidy
builds:
  - binary: 204
    env:
      - CGO_ENABLED=0
    goos:
      - aix
      - darwin
      - dragonfly
      - freebsd
      - js
      - linux
      - netbsd
      - openbsd
      - plan9
      - solaris
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - ppc64
      - ppc64le
      - riscv64
      - s390x
      - wasm
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
archives:
  - format: binary
